apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-yelb-job
spec:
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: kaniko-build-yelb-job
      namespace: default
    spec:
      restartPolicy: Never
      volumes:
      - name: workspace
      - name: kaniko-secret
        secret:
          secretName: kaniko-secret
      containers:
      - name: build-ui
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=/workspace/yelb-ui"
          - "--dockerfile=/workspace/yelb-ui/Dockerfile"
          - "--destination=gcr.io/waynean-shawn/yelb-ui:latest"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: kaniko-secret
          mountPath: /secret/
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secret/kaniko-secret.json
      - name: build-db
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=/workspace/yelb-db/Dockerfile"
          - "--context=/workspace/yelb-db"
          - "--destination=gcr.io/waynean-shawn/yelb-db:latest"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: kaniko-secret
          mountPath: /secret
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secret/kaniko-secret.json
      - name: build-appserver
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=/workspace/yelb-appserver"
          - "--dockerfile=/workspace/yelb-appserver/Dockerfile"
          - "--destination=gcr.io/waynean-shawn/yelb-appserver:latest"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: kaniko-secret
          mountPath: /secret/
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secret/kaniko-secret.json
      initContainers:
      - name: git-clone
        image: alpine
        command: ["sh", "-c"]
        args:
        - |
          apk add --no-cache git &&
          git clone https://github.com/shawnho1018/yelb.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
