kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: zthick-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
